# Generated by Django 3.2.8 on 2021-10-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('img', 'Image'), ('file', 'File'), ('mp3', 'Audio'), ('mp4', 'Video')], max_length=10)),
                ('solution', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
