# Generated by Django 3.2.8 on 2023-02-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20220228_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='key_derivation',
            field=models.CharField(choices=[('Hash', 'Hash derivation: sha256(code + user.id)'), (None, 'No derivation'), ('List', 'Coma-separated list code derivation: code[id % len]')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='order',
            field=models.IntegerField(default=0, help_text='Starts by 0'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='solution',
            field=models.TextField(),
        ),
    ]
