# Generated by Django 3.2.8 on 2023-04-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20230227_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, unique=True)),
                ('file', models.BinaryField(editable=True)),
                ('type', models.CharField(choices=[('Down', 'Downloadable file'), ('Script', 'Script generated with user id as argument')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='challenge',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='type',
            field=models.CharField(choices=[('img', 'Image'), ('file', 'File'), ('mp3', 'Audio'), ('mp4', 'Video'), ('none', 'No file')], max_length=10),
        ),
    ]
