# Generated by Django 3.2.18 on 2023-05-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20230422_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='key_derivation',
            field=models.CharField(blank=True, choices=[('Hash', 'Hash derivation: sha256(code + user.id)'), (None, 'No derivation'), ('List', 'Coma-separated list code derivation: code[id % len]')], max_length=5, null=True),
        ),
    ]
