# Generated by Django 3.2.18 on 2023-05-04 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0005_alter_challenge_key_derivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeuser',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge'),
        ),
        migrations.AlterField(
            model_name='challengeuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
